### ISSUE TITLE
About pretrain models.

### ISSUE THREAD

**Issue by docShen** [Westlake-AI/MogaNet#1]
Thank you for your work on MogaNet. When can the pre-training model be released? Thank you!

**Comment by docShen** [comment]
Ok, look forward to your latest progress! thanks!

**Comment by Lupin1998** [comment]
Hi, @docShen, thanks for your patience. We have released trained models and logs for MogaNet experiments of ImageNet-1K classification ([moganet-in1k-weights](https://github.com/Westlake-AI/MogaNet/releases/tag/moganet-in1k-weights)), COCO detection and instance segmentations ([moganet-det-weights](https://github.com/Westlake-AI/MogaNet/releases/tag/moganet-det-weights)), and ADE20K semantic segmentation ([moganet-seg-weights](https://github.com/Westlake-AI/MogaNet/releases/tag/moganet-seg-weights)). You can also download the full released files from [**Baidu Cloud**](https://pan.baidu.com/s/1d5MTTC66gegehmfZvCQRUA?pwd=z8mf) (z8mf). Free to ask me if you have further questions.

**Comment by Lupin1998** [comment]
I will close this issue if you no longer have any questions. Please feel free to reopen it or open a new issue if you meet new problems.
