### ISSUE TITLE
Unable to train model 

### ISSUE THREAD

**Issue by helloiammoon** [Westlake-AI/MogaNet#11]
Thanks for your significant paper. However, I encountered a problem when I ran the instruction code for training:
> File "/usr/local/lib/python3.10/dist-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
urllib.error.URLError: <urlopen error MaskRCNN: <urlopen error MogaNet_feat: <urlopen error [Errno 104] Connection reset by peer>>>

I appreciate your help!

**Comment by Lupin1998** [comment]
Hi, @helloiammoon. Sorry for the late reply, have you solved this issue yet? If this problem still occurs, please try to run object detection experiments under the dictionary of `./detection` with `dist_train.sh`, e.g., `PORT=23456 bash dist_train.sh configs/moganet/mask_rcnn_moganet_xtiny_fpn_1x_coco.py 8`. It error indicates the error of importing `MogaNet_feat` from `models/moganet.py`.

**Comment by Lupin1998** [comment]
Hi there, I will close this issue if there are no more questions. Feel free to contact us if you have new concerns.
