### ISSUE TITLE
Inquiry for code to train baseline

### ISSUE THREAD

**Issue by jimmylihui** [Westlake-AI/MogaNet#12]
Hi, 
Is there code for training the baseline?
Best,
Jiahui.Li

**Comment by Lupin1998** [comment]
Hi, @jimmylihui. Thanks for using MogaNet. This repository doesn't provide specific implementations of baselines. We recommend you refer to [OpenMixup](https://github.com/Westlake-AI/openmixup) for our benchmarks of vision backbones on ImageNet, [MMDetection](https://github.com/open-mmlab/mmdetection/tree/v2.26.0) and [MMSegmentation](https://github.com/open-mmlab/mmsegmentation/tree/v0.29.1) for the object detection and segmentation tasks, [MMPose](https://github.com/open-mmlab/mmpose/tree/v0.29.0) for the 2D and 3D pose estimation tasks. Another way to benchmark backbone baselines is to train the model name in our [training scripts](https://github.com/Westlake-AI/MogaNet/blob/main/TRAINING.md), e.g., training DeiT-S with 8 GPUs as `python -m torch.distributed.launch --nproc_per_node=8 --master_port=29501 train.py --model deit_small_patch16_224 --img_size 224 --drop_path 0.1 --batch_size 128 --lr 1e-3 --weight_decay 0.05 --update_freq 1`. This repository mainly provides the pre-training and fine-tuning implementations of MogaNet, while you can simply modify the training script to train the relevant baselines.

**Comment by Lupin1998** [comment]
Hi there, I will close this issue if there are no more questions. Feel free to contact us if you have new concerns.
