### ISSUE TITLE
Cascade Mask RCNN Configuration

### ISSUE THREAD

**Issue by dhkim0225** [Westlake-AI/MogaNet#16]
Congratulations on the ICLR24 acceptance.

I apologize if I missed it, but I was unable to find the cascade rcnn config file. Would it be possible to share it, or provide me with a link to its location?

**Comment by Lupin1998** [comment]
Hi, @dhkim0225. Thanks for your attention, and we apologize for the late reply! We have updated the config files and trained models/logs in the latest commit. Please refer to [detection](https://github.com/Westlake-AI/MogaNet/tree/main/detection) for details. Feel free to open a new issue if new questions occur.
