### ISSUE TITLE
Distributions of the interaction strength

### ISSUE THREAD

**Issue by PonyPinkPie** [Westlake-AI/MogaNet#17]
hi, thank you for your nice work.
could you offer us your code of `Distributions of the interaction strength` , which, i believe, is a new perspective of networks.

**Comment by Lupin1998** [comment]
Hi, @lyqqhgzj. Thanks for appreciating our work. You can find the official implementation of [multi-order interaction](https://arxiv.org/abs/2111.06236) in [bottleneck](https://github.com/nebularaid2000/bottleneck) or refer to our modified version in [RepBottleneck](https://github.com/Lupin1998/RepBottleneck).

**Comment by PonyPinkPie** [comment]
> Hi, @lyqqhgzj. Thanks for appreciating our work. You can find the official implementation of [multi-order interaction](https://arxiv.org/abs/2111.06236) in [bottleneck](https://github.com/nebularaid2000/bottleneck) or refer to our modified version in [RepBottleneck](https://github.com/Lupin1998/RepBottleneck).

thank you :)

**Comment by Lupin1998** [comment]
I will close this issue if there are no more questions.
