### ISSUE TITLE
Could you share the code for drawing multi-order interactions that shown in Fig. 3 of your paper?

### ISSUE THREAD

**Issue by VoXuanThuy** [Westlake-AI/MogaNet#4]
Thank you for the great work. I have a concern about how to draw the figure of the multi-order interactions.
Could you share the code? Thank you in advance.

**Comment by Jacky1128** [comment]
Hi, @VoXuanThuy, thanks for your attention. You can refer to Section B.1 of [MogaNet](https://arxiv.org/pdf/2211.03295.pdf) for more implementation details of multi-order interaction. As for the source code, please refer to [Representation Bottleneck](https://github.com/Nebularaid2000/bottleneck) and [draw_figures.py](https://github.com/Nebularaid2000/bottleneck/blob/main/draw_figures.py) for the interaction figure drawing. I hope this will be helpful to you and feel free to ask me if you have more problems with MogaNet.

**Comment by Lupin1998** [comment]
Hi, @VoXuanThuy. We hope the [official implementation](https://github.com/Nebularaid2000/bottleneck) of [Representation Bottleneck](https://arxiv.org/abs/2111.06236) could help you. Here, we also upload a modified implementation version ([RepBottleneck-main.zip](https://github.com/Westlake-AI/MogaNet/files/10834541/RepBottleneck-main.zip)) for our experiments (please do not distribute). You can ask me or contact the author of [Representation Bottleneck](https://arxiv.org/abs/2111.06236) if some questions occur. I will close this issue if there is no more question.
