### ISSUE TITLE
Some small issues about detection and segmentation

### ISSUE THREAD

**Issue by xuesongnie** [Westlake-AI/MogaNet#7]
是否需要冻结前几层的参数，还是全部网络放开训练效果好一点，因为看到代码里面没有写关于冻结参数的部分，所以有这个小问题。

**Comment by Lupin1998** [comment]
Hi, @xuesongnie. Thanks for your question. We haven't frozen the parameters of the backbones in downstream tasks. As for COCO detection tasks, we set `norm_eval=True` as ResNet but not freeze stage-1. I hope this would help you.
